### PR TITLE
add unwrap_or for Church options, add doctest for map_or

### PR DESCRIPTION
**Pull request by billpmurphy**

### CODE REVIEW

**Comment by ljedrz** [comment]
Looks good! I'll merge it right after the 2.0 branch.

**Comment by ljedrz** [comment]
Actually it will need a bit of rebasing now; while you're at it, could you rename the test function `test_unwrap_or()` to `church_unwrap_or()`? It will be uniform with the other names.

**Comment by billpmurphy** [comment]
Updated!

**Comment by billpmurphy** [comment]
Actually, I'm wondering if it makes sense to prefix the function names in the `church::option` module with `option_`, e.g. `option_unwrap_or`. Some of the other functions in `std::option::Option` are `map`, `and`, and `or`, which overlap with the names in `church::lists`.

**Comment by ljedrz** [comment]
I've thought about potential name overlapping, but the function name can always be used with its module name to disambiguate, so it shouldn't be a big deal.

**Pull request merged**
