### PR TITLE
add outline of Church option type

### PR DESCRIPTION
**Pull request by billpmurphy**
Simple implementation of an option type encoded as functions. Feel free to reject if you believe this doesn't fit in with the rest of what's in the `church` module.

I didn't add anything to `impl Term`, I'm not sure what (if anything) should be added there for options.

### CODE REVIEW

**Comment by ljedrz** [comment]
I'm all for adding other Church data types (especially when they are as useful as `Option<T>`), but I always try to provide some reference backing them, at least in the module's documentation; could you provide one?

**Comment by billpmurphy** [comment]
This took me down a fun research rabbit hole.

The [Wikipedia article on Church encoding](https://en.wikipedia.org/wiki/Church_encoding) mentions "tagged unions" but doesn't elaborate. There are few papers (e.g. [1](https://ifl2014.github.io/submissions/ifl2014_submission_13.pdf),  [2](https://link.springer.com/chapter/10.1007/978-3-642-40355-2_12), [3](http://okmij.org/ftp/tagless-final/course/Boehm-Berarducci.html)) that mention the Church encoding of algebraic data types as "more common" than Morgensen-Scott encoding or Boehm-Berarducci encoding but don't provide a reference. The Wikipedia article on [Morgensen-Scott encoding](https://en.wikipedia.org/wiki/Mogensen%E2%80%93Scott_encoding#Comparison_to_the_Church_encoding) mentions this but also lacks a reference.

[This](http://repository.ubn.ru.nl/bitstream/handle/2066/17274/13362.pdf?sequence=1) is the earliest paper I could find that describes how to Church-encode arbitrary algebraic data types. There also are a bunch of blog posts (e.g. [1](https://www.quora.com/How-are-Lambda-calculus-and-Algebraic-data-type-related), [2](http://programmable.computer/posts/church_encoding.html), [3](https://medium.com/@curtis.lusmore/intuition-of-church-encoding-5b9cf7d82577), [4](http://www.cbdumas.com/posts/church_encoding.html)) that demonstrate the same concept as well with Option/Maybe as an example.

Since there's no drop-in Wikipedia reference, do you have a preference for what to cite?

**Comment by ljedrz** [comment]
Hmm, there's no clear winner, but I guess we could leave it for later. There are some minor details in this commit that I'd like to adjust when I have time, but overall I think this is a very nice addition to the Church collection.

**Comment by ljedrz** [comment]
As for adding related `impl Term` methods I'm not sure myself; on one hand, there are some of them available for Church lists, numerals and pairs and they are much faster than their Church equivalents; on the other, they aren't the core functionality of this library and most users probably aren't concerned with the performance. They may even be dropped altogether in version 2.0.

**Pull request merged**
